#!/bin/sh
export CPATH="$CPATH:$HOME/include"
export LIBRARY_PATH="$LIBRARY_PATH:$HOME/lib"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/lib"


#!/bin/sh
gcc -O3 -march=native -mtune=native -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare  -I. -Isubroutines -DKATNUM=`cat KATNUM` "-DCRYPTO_NAMESPACE(x)=x" "-D_CRYPTO_NAMESPACE(x)=_##x" -o ../kyber-backdoor/ref/libmceliece348864avx.so nist/kat_kem.c nist/rng.c benes.c bm.c controlbits.c decrypt.c encrypt.c fft.c fft_tr.c gf.c int32_minmax_x86.c int32_sort.c operations.c pk_gen.c sk_gen.c vec256.c vec.c  consts.S syndrome_asm.S transpose_64x256_sp_asm.S transpose_64x64_asm.S update_asm.S vec128_mul_asm.S vec256_mul_asm.S vec_mul_asm.S vec_mul_sp_asm.S vec_reduce_asm.S   -L. -lkeccak -lcrypto -ldl -shared -fPIC  -fomit-frame-pointer -fwrapv


cp -r ../kyber-backdoor/ref/libmceliece348864avx.so ../kyber-backdoor/avx2/libmceliece348864avx.so